### ISSUE TITLE
repo.protect_branch out-of-date?

### ISSUE THREAD

**Issue by moltob** [PyGithub/PyGithub#711] opened 2018-02-26 17:12 UTC
I was trying to use the above-mentioned API and get a 404 not found in return. Looking at the issued REST call it seems not to match the current API.

The following REST call is issued:

```
PATCH https:/<url>/api/v3/repos/<org>/<repo>/branches

{'Accept': 'application/vnd.github.loki-preview+json', 'Authorization': 'token (oauth token removed)', 'User-Agent': 'PyGithub/Python', 'Content-Type': 'application/json'}

{"protection": {"enabled": true, "required_status_checks": {"enforcement_level": "non_admins"}}}
```

However, Github's API docs look like they expect it [differently](https://developer.github.com/enterprise/2.12/v3/repos/branches/#update-branch-protection). E.g. the endpoint URL holds ``/protection`` and the data keys also seem different (no ``protection``, no ``enabled``, ...).

Am I missing something or is the Python API out-of-date?

Thanks a lot!

**Comment by sfdye** [comment] 2018-02-27 02:31
@moltob Thanks a lot for reporting. You are right, GitHub constantly updates it API and we are absolutely not up-to-update on this change. Feel free to make a PR to fix it!

**Comment by sfdye** [comment] 2018-03-22 15:12
I think this might link to #527

**Comment by sfdye** [comment] 2018-04-07 17:00
Closing this as a duplicate of #736

**Closed by sfdye** 2018-04-07 17:00 UTC
Labels: bug
