### ISSUE TITLE
gittodoist clone uses PyGithub

### ISSUE THREAD

**Issue by hasii2011** [PyGithub/PyGithub#1811] opened 2020-12-31 00:09 UTC
Please list this project:  https://github.com/hasii2011/gittodoistclone

as a user of this API

This is a wxPython Mac application that can read your github repositories and converts your github issues to todoist tasks.

**Comment by s-t-e-v-e-n-k** [comment] 2021-03-08 03:15
Duplicate of (already fixed) #1677

**Closed by s-t-e-v-e-n-k** 2021-03-08 03:15 UTC
