### ISSUE TITLE
Installation.get_repos() appears to be broken - always throws BadCredentialsException

### ISSUE THREAD

**Issue by eap** [PyGithub/PyGithub#2504] opened 2023-04-21 23:25 UTC
Is there anyone using this method? The only other reference to my issue is two comments in this stale pull request #1791 which seems to agree with my findings. Alternatively, we are both guilty of user error.

To recreate the issue:
1) Create a github app with read access to repositories.
2) Install it in your user account granting access to all repositories, or at least one private repo used for this example.
3) Create and download an application private key ".pem" file.
4) Note the application ID.

Initialize the integration and installation. Ensure that the installation credentials work for mundane requests (get repo).
```
$ python3
Python 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
>> from github import *
>> with open("mykeyfile.pem", "r") as f:
...  private_key = f.read().strip()

>> app_id = "123456" // use your application id.
>> integration = github.GithubIntegration(app_id, private_key)
>> installation = integration.get_repo_installation('myuser', 'my-private-repo')
>> token = integration.get_access_token(installation.id).token
>> g = Github(token)
>> g.get_repo('myuser/my-private-repo')
Repository(full_name="myuser/my-private-repo")
```

The failure

```
>> print('Using the same installation, I get this failure')
>> installation.get_repos()
<github.PaginatedList.PaginatedList object at 0x11248d450>
>>> hitting_the_api_now = [r for r in installation.get_repos()]
File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/users/Ubuntu/test_error/.venv/lib/python3.11/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
                  ^^^^^^^^^^^^
  File "/users/Ubuntu/test_error/.venv/lib/python3.11/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/users/Ubuntu/test_error/.venv/lib/python3.11/site-packages/github/PaginatedList.py", line 201, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/Ubuntu/test_error/.venv/lib/python3.11/site-packages/github/Requester.py", line 398, in requestJsonAndCheck
    return self.__check(
           ^^^^^^^^^^^^^
  File "/users/Ubuntu/test_error/.venv/lib/python3.11/site-packages/github/Requester.py", line 423, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by eap** [comment] 2023-04-21 23:26
In case it helps, here's my environment;

```
$ pip freeze
boto3==1.26.115
botocore==1.29.115
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
cryptography==40.0.2
Deprecated==1.2.13
idna==3.4
jmespath==1.0.1
pycparser==2.21
PyGithub==1.58.1
PyJWT==2.6.0
PyNaCl==1.5.0
python-dateutil==2.8.2
requests==2.28.2
s3transfer==0.6.0
six==1.16.0
urllib3==1.26.15
wrapt==1.15.0
```

**Comment by hcordobest** [comment] 2023-05-04 16:52
May be a dupe of #1753 ?

**Comment by eap** [comment] 2023-05-04 20:10
> May be a dupe of #1753 ?

I don't think so - #1753 appears to be about user token credentials. This issue seems to be specific to installation objects. A quick reading of the source shows that the Installation is using the same requester (and same jwt) as the parent integration object (see [GithubIntegration.py](https://github.com/PyGithub/PyGithub/blob/master/github/GithubIntegration.py#LL86C16-L86C28)). I think the installation needs an installation token (weirdly enough, fetched using `Integration.get_installation_token`) before it would be capable of querying properties of the installation. Using the integration jwt clearly doesn't work.

**Closed** 2023-06-13 06:35 UTC
