### ISSUE TITLE
Creating secret at org level

### ISSUE THREAD

**Issue by johndrusso** [PyGithub/PyGithub#2105] opened 2021-11-10 15:29 UTC
Using pyGithub v1.55, I've had success creating repo-level secrets but not org-level secrets. I receive a "AttributeError: 'Organization' object has no attribute 'create_secret'", even though I see the method in your code and in your documentation.  Is there a step I could be missing? If I execute get_organization on my org and do a dir of the object, there's no 'create_secret' attribute listed as seen below:

> ORG = "redacted"
> github_client = Github("redacted")
> org = github_client.get_organization(ORG)
> dir(org)
['CHECK_AFTER_INIT_FLAG', '_CompletableGithubObject__complete', '_CompletableGithubObject__completed', '_GithubObject__makeSimpleAttribute', '_GithubObject__makeSimpleListAttribute', '_GithubObject__makeTransformedAttribute', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_avatar_url', '_billing_email', '_blog', '_collaborators', '_company', '_completeIfNeeded', '_completeIfNotSet', '_created_at', '_default_repository_permission', '_description', '_disk_usage', '_email', '_events_url', '_followers', '_following', '_gravatar_id', '_has_organization_projects', '_has_repository_projects', '_headers', '_hooks_url', '_html_url', '_id', '_initAttributes', '_issues_url', '_location', '_login', '_makeBoolAttribute', '_makeClassAttribute', '_makeDatetimeAttribute', '_makeDictAttribute', '_makeDictOfStringsToClassesAttribute', '_makeFloatAttribute', '_makeIntAttribute', '_makeListOfClassesAttribute', '_makeListOfDictsAttribute', '_makeListOfIntsAttribute', '_makeListOfListOfStringsAttribute', '_makeListOfStringsAttribute', '_makeStringAttribute', '_makeTimestampAttribute', '_members_can_create_repositories', '_members_url', '_name', '_owned_private_repos', '_parentUrl', '_plan', '_private_gists', '_public_gists', '_public_members_url', '_public_repos', '_rawData', '_repos_url', '_requester', '_storeAndUseAttributes', '_total_private_repos', '_two_factor_requirement_enabled', '_type', '_updated_at', '_url', '_useAttributes', 'add_to_members', 'add_to_public_members', 'avatar_url', 'billing_email', 'blog', 'collaborators', 'company', 'convert_to_outside_collaborator', 'create_fork', 'create_hook', 'create_migration', 'create_project', 'create_repo', 'create_team', 'created_at', 'default_repository_permission', 'delete_hook', 'description', 'disk_usage', 'edit', 'edit_hook', 'email', 'etag', 'events_url', 'followers', 'following', 'get__repr__', 'get_events', 'get_hook', 'get_hooks', 'get_installations', 'get_issues', 'get_members', 'get_migrations', 'get_outside_collaborators', 'get_projects', 'get_public_members', 'get_repo', 'get_repos', 'get_team', 'get_team_by_slug', 'get_teams', 'gravatar_id', 'has_in_members', 'has_in_public_members', 'has_organization_projects', 'has_repository_projects', 'hooks_url', 'html_url', 'id', 'invitations', 'invite_user', 'issues_url', 'last_modified', 'location', 'login', 'members_can_create_repositories', 'members_url', 'name', 'owned_private_repos', 'plan', 'private_gists', 'public_gists', 'public_members_url', 'public_repos', 'raw_data', 'raw_headers', 'remove_from_members', 'remove_from_membership', 'remove_from_public_members', 'remove_outside_collaborator', 'repos_url', 'setCheckAfterInitFlag', 'total_private_repos', 'two_factor_requirement_enabled', 'type', 'update', 'updated_at', 'url']

**Comment by s-t-e-v-e-n-k** [comment] 2021-11-10 21:59
Organization.create_secret() has not been released yet. This is a duplicate of #1873.

**Closed by s-t-e-v-e-n-k** 2021-11-10 21:59 UTC
