### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by gerardsegarra** [PyGithub/PyGithub#2170] opened 2022-02-08 16:16 UTC
Hi! There's been a few since a new version was released. There are some interesting features in the main branch. Are you planning on releasing a new one any time soon?

Thanks in advance!

**Comment by dclayton-godaddy** [comment] 2022-03-04 21:39
cc @xmo-odoo @s-t-e-v-e-n-k

**Comment by alexef** [comment] 2022-04-08 08:31
duplicate of: https://github.com/PyGithub/PyGithub/issues/2139

**Comment by jeffwidman** [comment] 2022-10-26 08:15
This should be closed now that https://pypi.org/project/PyGithub/1.56/ was tagged.

**Comment by s-t-e-v-e-n-k** [comment] 2022-10-26 08:18
And doing so, thanks!

**Closed by s-t-e-v-e-n-k** 2022-10-26 08:18 UTC
