### ISSUE TITLE
Incorrect PyJWT Version Dependency

### ISSUE THREAD

**Issue by samamorgan** [PyGithub/PyGithub#1886] opened 2021-03-22 23:10 UTC
Release v1.54.1 introduced PR #1797, pinning `PyJWT<2.0`. This makes this package incompatible with other libraries that have dropped Python 3.5 support and use PyJWT, as all require `PyJWT>=2.0`. This forces me to use an outdated version of this package to maintain my current dependencies.

This change goes against the stated intentions of PR #1770, dropping Python 3.5 support.

**Comment by s-t-e-v-e-n-k** [comment] 2021-03-22 23:23
Duplicate of #1832

**Closed by s-t-e-v-e-n-k** 2021-03-22 23:23 UTC
