### ISSUE TITLE
Consider minting a release

### ISSUE THREAD

**Issue by akhmerov** [PyGithub/PyGithub#1870] opened 2021-03-09 12:24 UTC
The recently merged #1681 implements important new functionality: support for secrets. Therefore I would like to suggest minting a release. If a direct release doesn't fit into the plan, I would like to know the rough time scale until the release.

Thank you in advance :heart:!

**Comment by s-t-e-v-e-n-k** [comment] 2021-03-10 00:56
Duplicate of #1847

**Closed by s-t-e-v-e-n-k** 2021-03-10 00:56 UTC
