### ISSUE TITLE
Can't retrieve total count of a file's commits

### ISSUE THREAD

**Issue by khof312** [PyGithub/PyGithub#896] opened 2018-09-05 12:20 UTC
I am trying to retrieve a list of all previous commits for a file. While I am able to retrieve a PaginatedList using `.get_commits`, and retrieve individual pages from this list, I found the following problems:

1. The PaginatedList object does not have the documented `.totalCount` attribute 
2. If I run `len()` on the list I am told that it has no `len()` property. 

I am following the instructions about the PaginatedList class on line 100 [here](https://github.com/PyGithub/PyGithub/blob/master/github/PaginatedList.py).

MWE:

```
from github import Github
g = Github( ... )           #  <- authentication removed
user = g.get_user('PyGithub')
repo = user.get_repo('PyGithub')

### Working fine
repo.get_commits(path='README.md').get_page(0)

### Returns NoneType
type(repo.get_commits(path='README.md').totalCount)

### Returns "TypeError: object of type 'PaginatedList' has no len()"
len(repo.get_commits(path='README.md'))
```

**Comment by sfdye** [comment] 2018-09-05 12:27
Duplicate of #886

**Comment by khof312** [comment] 2018-09-05 15:10
Yes thank you. Probably this can be closed, sorry I didn't see the other issue.

**Closed** 2018-09-05 15:11 UTC
