### ISSUE TITLE
Datetime returned is naive, should be UTC

### ISSUE THREAD

**Issue by dpocock** [PyGithub/PyGithub#512] opened 2017-01-02 19:54 UTC
If I query an issue and access ```issue.created_at.tzinfo```, it is ```None```, indicating a naive datetime object

The values always appear to be UTC values so the ```tzinfo``` should be set to UTC (offset 0)

If the values are naive, all kinds of unusual bugs can occur in programs that try to insert the values into databases or other systems that assume a naive datetime is in local time.

**Comment by bbi-yggy** [comment] 2018-07-30 18:45
It would be great if the main Github object provided a mechanism for setting desired time zone, and that all retrieved datetimes would respect it. Alternatively, make all times timezone aware based on their local context - for example the datetime on a commit should indicate the timezone where the commit occurred.

**Comment by bbi-yggy** [comment] 2018-07-30 18:55
By the way, for anyone arriving here who wants to get the PyGithub datetimes converted to a particular time zone, this should help:
```
import pytz  # Need to "pip install pytz"
def LocalDateTimeFromUTC(utc):
    tzLocal = pytz.timezone('America/Vancouver')  # insert your time zone here (list available here: https://stackoverflow.com/questions/13866926/is-there-a-list-of-pytz-timezones)
    return pytz.utc.localize(utc).astimezone(tzLocal)
```

**Comment by docktermj** [comment] 2019-09-10 23:58
I ran into this issue with when coding

```python
                        created_at_epoch = int(comment.created_at.timestamp())
```

https://github.com/docktermj/python-github-tasks/blob/5014d05990b181aec36b9fe2c8374450ec66dad8/github-tasks.py#L688

**Comment by docktermj** [comment] 2019-09-11 02:38
Is this a reasonable work-around?

```python
local_timezone = pytz.timezone("GMT")
created_at = local_timezone.localize(comment.created_at)
created_at_epoch = int(created_at.timestamp())
```

**Comment by docktermj** [comment] 2019-09-11 02:44
@dpocock @bbi-yggy @sfdye @s-t-e-v-e-n-k 

This is no longer a stale issue.   How can this issue be reopened?   ...or do I open another issue?

**Comment by docktermj** [comment] 2019-09-11 02:45
@sfdye,  thank you!  I'll close #1218

**Comment by docktermj** [comment] 2019-11-18 01:13
@dpocock @bbi-yggy @sfdye @s-t-e-v-e-n-k

This is no longer a stale issue. How can this issue be reopened? ...or do I open another issue?

**Comment by docktermj** [comment] 2020-01-23 01:52
@dpocock @bbi-yggy @sfdye @s-t-e-v-e-n-k

This is no longer a stale issue. How can this issue be reopened? ...or do I open another issue?

Or is it fixed?

**Comment by dato** [comment] 2020-06-14 05:29
It'd be nice to see this fixed. It can be trivially fixed in application code:

```
author_date = commit.author.date.replace(tzinfo=datetime.timezone.utc)
```

but a strong argument for fixing it in the library is that it's easy to forget to replace tzinfo _on every single date use_.

Thanks for considering.

**Comment by s-t-e-v-e-n-k** [comment] 2020-06-14 08:19
This might be a little bit of 'perfect is the enemy of good', but I've been wanting to solve this by allowing users to pass in a timezone to the Github() constructor, *but* there's no good library without awkward sharp edges to parse things like 'Australia/Sydney' and 'Europe/Berlin' into what GitHub is expecting. But it has been a little while since I dug into this code.

**Comment by dato** [comment] 2020-09-23 17:35
Given that times from Github API always come in UTC, even when the original (commit date was not UTC), it may be best to leave them as naive datetime objects after all.

**Comment by Saviq** [comment] 2020-09-25 06:55
Well, if it's known they're in UTC, why would keeping them naive be better?

**Comment by dato** [comment] 2020-09-25 07:29
Because they're lossy. They're (if I recall correctly) unconditionally in UTC (`+0000`), where as the actual commit as stored in Git itself, does record the timezone offset (e.g. `+0300`).

So I believe it's better to keep them naive, because it allows for the following semantics:

  - if PyGithub gives you a naive datetime, it's in UTC, as per Github's default behavior
  - if PyGithub gives you a non-naive datetime, it's because Github started exposing the timezone information properly (`+0300` in the date string), and we've applied it for you

If you start marking Github's current behavior as non-naive, there won't be a way to distinguish a proper UTC timestamp (recorded in Git as `+0000`), or Github defaulting to UTC.

(Well, re: "there won't be a way", there could be others; the one I proposed above wouldn't work.)

----

It's true that it imposes a bit more work on library users at the present time—but, as a library user, I prefer this kind of control. (Personally, for example, upon receiving a naive date, I apply the timezone of the _server_ the commit was generated in. Which is not quite as having the actual metadata from Git, but it's close enough for my usecase.)

**Comment by RJPercival** [comment] 2021-03-05 10:39
@dato The problem is that users will deal the naive datetimes by calling `my_datetime.replace(tzinfo=datetime.timezone.utc)` (as you can see in this thread). That works fine while you're returning naive datetimes but, if you ever made your proposed change of returning non-naive datetimes with a non-UTC timezone, you'd introduce bugs into every bit of code that does that (since it'll overwrite the timezone with UTC without adjusting the time appropriately). Really, the only options available to PyGithub IMO are to keep returning naive datetimes or to return non-naive datetimes with the UTC timezone (and save your users having to implement that workaround).

**Closed** 2023-06-28 19:47 UTC
Labels: improvement

**Comment by awaisdar001** [comment] 2023-08-21 13:14
I hope this be helpful for you. 

```
from github import Github
import pytz
from datetime import datetime

# Create a Github instance with your access token
access_token = 'YOUR_ACCESS_TOKEN'
github = Github(access_token)

# Get the repository
repository = github.get_repo("owner/repo")

# Get a specific pull request (replace with the actual pull request number)
pull_request_number = 123
pull_request = repository.get_pull(pull_request_number)

# Retrieve the created_at timestamp
created_at_utc = pull_request.created_at

# Define timezone offsets for Pakistan (PKT) and Kuwait
timezone_offsets = {
    'PKT': timedelta(hours=5),  # Pakistan Time (UTC+5)
    'Kuwait': timedelta(hours=3),  # Kuwait Time (UTC+3)
    ...
}

# Convert the timestamp to Pakistan Time (PKT) and Kuwait Time
created_at_pkt = created_at_utc + timezone_offsets['PKT']
created_at_kuwait = created_at_utc + timezone_offsets['Kuwait']

print(f'PKT Time: {created_at_pkt}')
print(f'Kuwait Time: {created_at_kuwait}')

```
