### ISSUE TITLE
pyjwt causing issues with GithubIntegration

### ISSUE THREAD

**Issue by edouardpoitras** [PyGithub/PyGithub#627] opened 2017-09-12 16:28 UTC
I encountered this issue when using the GithubIntegration class:

    import github
    app_id = aaaa
    private_key = open('key.pem').read()
    installation_id = bbbbb
    integration = github.GithubIntegration(app_id, private_key)
    token = integration.get_access_token(installation_id)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/eddie/.local/lib/python3.6/site-packages/github/MainClass.py", line 692, in get_access_token
        data=response_text
        github.GithubException.GithubException: 401 {"message":"Invalid credentials","documentation_url":"https://developer.github.com/v3"}

In the GithubIntegration.create_jwt() function line 636:
Replaced:

    return jwt.encode(
                payload,
                key=self.private_key,
                algorithm="RS256"
            )
With:

    from jose import jwt as JWT                                                                 
    return JWT.encode(payload, self.private_key, 'RS256')

Trying again...

    import github
    app_id = aaaa
    private_key = open('Downloads/test.pem').read()
    installation_id = bbbbb
    integration = github.GithubIntegration(app_id, private_key)
    token = integration.get_access_token(installation_id)
    token
    InstallationAuthorization(expires_at=2017-09-12 17:11:32)

Not sure what the difference is between the pyjwt and python-jose implementations are, but pyjwt doesn't seem to work for me.

Looks like python-jose was the original library used for jwt tokens and that was switched to pyjwt in issue #542 on March 27th.

**Comment by jasonwhite** [comment] 2017-11-27 23:03
Duplicate of #588. Should be fixed in the next release.

**Closed by jasonwhite** 2017-11-27 23:03 UTC
