### ISSUE TITLE
Can I get the limit for search now?

### ISSUE THREAD

**Issue by Strikersb** [PyGithub/PyGithub#895] opened 2018-09-04 10:41 UTC
I get self.g.rate_limiting got `(4993, 5000)`

But the search limit is different, with only 30 requests per minute.

Excuse me, I didn't find the corresponding document, or PyGithub does not have this function now.

thanks

**Comment by Strikersb** [comment] 2018-09-04 10:43
document: https://developer.github.com/v3/search/#rate-limit

**Comment by sfdye** [comment] 2018-09-04 11:51
Possible duplicate of #895

**Comment by Strikersb** [comment] 2018-09-04 13:04
@sfdye  Thank you very much. By the way, when will `get_search_rate_limit()` be completed?

**Comment by sfdye** [comment] 2018-09-05 02:58
When I get some free time, will take a look. Merging with #553 .

**Closed by sfdye** 2018-09-05 02:58 UTC

**Comment by sfdye** [comment] 2018-09-05 04:36
Fixed in #553
