### ISSUE TITLE
Allow newer PyJWT releases

### ISSUE THREAD

**Issue by fabaff** [PyGithub/PyGithub#1838] opened 2021-02-05 14:41 UTC
[PyJWT 2.0.1](https://pyjwt.readthedocs.io/en/stable/changelog.html) was published recently.

https://github.com/PyGithub/PyGithub/blob/34d097ce473601624722b90fc5d0396011dd3acb/setup.py#L101

The current version constrain (`<2.0`) will break the build on NixOS. 

Do you have any plans to support PyJWT>2.0? 

Thanks

**Comment by s-t-e-v-e-n-k** [comment] 2021-02-05 23:28
Duplicate of #1832

**Closed by s-t-e-v-e-n-k** 2021-02-05 23:28 UTC
