### ISSUE TITLE
Branch Protection calls missing

### ISSUE THREAD

**Issue by kbessas** [PyGithub/PyGithub#736] opened 2018-03-26 11:28 UTC
I believe these are still missing:

https://developer.github.com/v3/repos/branches/#get-branch-protection
https://developer.github.com/v3/repos/branches/#update-branch-protection
https://developer.github.com/v3/repos/branches/#remove-branch-protection
https://developer.github.com/v3/repos/branches/#get-required-status-checks-of-protected-branch
https://developer.github.com/v3/repos/branches/#update-required-status-checks-of-protected-branch
https://developer.github.com/v3/repos/branches/#remove-required-status-checks-of-protected-branch

Anyone willing to create a pr for these?

**Comment by sfdye** [comment] 2018-03-29 10:18
Link to #527

**Comment by sfdye** [comment] 2018-04-07 17:01
Closing this as a duplicate of #586

**Closed by sfdye** 2018-04-07 17:01 UTC
Labels: feature request
