### ISSUE TITLE
can we set branch permission ?

### ISSUE THREAD

**Issue by thinksabin** [PyGithub/PyGithub#610] opened 2017-08-07 11:02 UTC
Hi,

I was checking into the git api and pygithub on any method that we can set the branch permission with readonly where no code can be push or merged in specific branch. eg: locking master branch using pygithub.

thanks

**Comment by sfdye** [comment] 2018-04-07 17:01
Closing this as a duplicate of #586

**Closed by sfdye** 2018-04-07 17:01 UTC
