### ISSUE TITLE
Implement get_license as provided in preview by GitHub

### ISSUE THREAD

**Issue by BrunoVernay** [PyGithub/PyGithub#398] opened 2016-04-24 14:33 UTC
GitHub does the job of parsing the repository's License file to extract License info https://developer.github.com/v3/licenses/#get-a-repositorys-license

It would be nice to have this available in the PyGithub.

**Comment by sfdye** [comment] 2018-03-18 03:38
Close as duplicate of #508

**Closed** 2018-04-06 01:17 UTC
