### ISSUE TITLE
missing allow_force_push / allow_deletions on branch protection

### ISSUE THREAD

**Issue by donatelloOo** [PyGithub/PyGithub#1992] opened 2021-07-07 14:50 UTC
The following properties are not supported by current API, neither on get or update methods about branch protection:
* branch: allow_force_push
* branch: allow_deletions
* branch: required_linear_history
see: https://pygithub.readthedocs.io/en/latest/github_objects/BranchProtection.html
see: https://pygithub.readthedocs.io/en/latest/github_objects/Branch.html#github.Branch.Branch.edit_protection

![image](https://user-images.githubusercontent.com/29257279/124781005-595cf800-df43-11eb-9927-e6085d28ab5c.png)

whereas GitHub API manage them.
see: https://docs.github.com/en/rest/reference/repos#update-branch-protection

Actually the raw data of read BranchProtection object contains these properties, so a workaround is possible, but NOT for updating these settings.
So we cannot use this API to fully enforce github settings :/

I guess it's not that hard to just add these properties, could you ?

**Comment by treee111** [comment] 2021-07-28 13:45
dublicate to https://github.com/PyGithub/PyGithub/issues/1716 in my opinion?

**Comment by s-t-e-v-e-n-k** [comment] 2021-08-10 12:56
Yes, duplicate of #1716

**Closed by s-t-e-v-e-n-k** 2021-08-10 12:56 UTC
