### ISSUE TITLE
repo.get_stats_contributors() return None and how get Retry-After.

### ISSUE THREAD

**Issue by kinmanz** [PyGithub/PyGithub#493] opened 2016-11-27 16:22 UTC
I have 100 repositories objects and make 100 sequential requests on them 

`repo.get_stats_contributors() `

By time this requests start to return None objects, I sure it happens because of abusing of rate limit, in that case I want to get **Retry-After** header to wait and continue again.

https://developer.github.com/guides/best-practices-for-integrators/#dealing-with-rate-limits

How can I get the header?

**Comment by sfdye** [comment] 2018-06-22 08:33
I suspect this is not due to rate limit but rather a duplicate of #564. Github calculates this stats on demand so we need to wait for some time for it to finish. #791 should resolve it.

**Comment by sfdye** [comment] 2018-06-22 08:56
Closing as #791 is merged.

**Closed by sfdye** 2018-06-22 08:56 UTC
