### ISSUE TITLE
There is no way to fetch the repositories associated with an installation_id

### ISSUE THREAD

**Issue by jainankit** [PyGithub/PyGithub#1808] opened 2020-12-30 06:52 UTC
I recently upgraded PyGithub to version 1.54. Looks like in that release you have removed the method to fetch Installation object using installation_id: https://github.com/PyGithub/PyGithub/pull/1738

Earlier, I could get the installation object by `installation_id`, and then call `installation.get_repos()` to fetch all accessible from the installation. Now there is no way to do this using PyGithub. The other `get_installation` method requires providing organization name, but that is not available when the Github app is installed.

As a workaround, I had to manually make a GET request with the auth token to:
```
"https://api.github.com/installation/repositories"
```

But would be great to bring back that method.

**Comment by s-t-e-v-e-n-k** [comment] 2020-12-31 00:24
Duplicate of #1776

**Closed by s-t-e-v-e-n-k** 2020-12-31 00:24 UTC
