### ISSUE TITLE
Organization Repository Creation Attempt Yields 403

### ISSUE THREAD

**Issue by rgajason** [PyGithub/PyGithub#1705] opened 2020-09-25 03:34 UTC
Module information:
```
Deprecated==1.2.10
PyGithub==1.53
PyJWT==1.7.1
```

Using an access token with full rights:
```
from github import Github
g = Github('my-token-here')
org = g.get_organization('my-org')
org.login
```

> 'my-org'

Attempting to create a new repository in the organization fails with a 403.
```
r = org.create_repo('test-repo', private=True)
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".../lib/python3.7/site-packages/github/Organization.py", line 581, in create_repo
>     "POST", self.url + "/repos", input=post_parameters
>   File ".../lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
>     verb, url, parameters, headers, input, self.__customConnection(url)
>   File ".../lib/python3.7/site-packages/github/Requester.py", line 342, in __check
>     raise self.__createException(status, responseHeaders, output)
> github.GithubException.GithubException: 403 {"message": "You'll need a different OAuth scope to create a private repository. Please see the documentation for full details.", "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-repository-for-the-authenticated-user"}

If I remove `private=True` I get a 403 with a different message:
```
r = org.create_repo('test-repo')
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".../lib/python3.7/site-packages/github/Organization.py", line 581, in create_repo
>     "POST", self.url + "/repos", input=post_parameters
>   File ".../lib/python3.7/site-packages/github/Requester.py", line 319, in requestJsonAndCheck
>     verb, url, parameters, headers, input, self.__customConnection(url)
>   File ".../lib/python3.7/site-packages/github/Requester.py", line 342, in __check
>     raise self.__createException(status, responseHeaders, output)
> github.GithubException.GithubException: 403 {"message": "You need admin access to the organization before adding a repository to it.", "documentation_url": "https://docs.github.com/rest/reference/repos#create-an-organization-repository"}

I'm able to create the repository from the web UI (same user account) and retrieve that repo configuration via PyGithub.

**Comment by rgajason** [comment] 2020-09-25 13:24
A colleague of mine did some further research and this issue seems to be a combination of limitations in the current stable GH API and our organization setup.

Our organization has both "public" and "private" repositories disabled (we use "internal" repos).  In the v3 API if you don't say `private=True` it tries to create a "public" repository (vs just using the organization default).  The v3 API also does not support "internal" repos.

In order to create "internal" repositories you have to change your `Accept` header to `application/vnd.github.nebula-preview+json` and include `visibility=internal` in the body.

So it would seem that the answer here is to update the `Accept` header and data.  Is there a parameter that can be passed to change the `Accept` header in PyGithub?

**Comment by s-t-e-v-e-n-k** [comment] 2020-10-02 05:22
Thanks for the investigation! This is a duplicate of #1446

**Closed by s-t-e-v-e-n-k** 2020-10-02 05:22 UTC
