### ISSUE TITLE
enable allow_delete option from pygithub

### ISSUE THREAD

**Issue by Baitanik** [PyGithub/PyGithub#2021] opened 2021-08-10 11:05 UTC
in the existing implementation of updaing branch protection rule i am not able to get the option to allow_deletions or allow_force_pushes... 

https://pygithub.readthedocs.io/en/latest/github_objects/Branch.html#github.Branch.Branch.edit_protection

https://docs.github.com/en/enterprise-server@2.22/rest/reference/repos#update-branch-protection

Could you please let me know how can update the branch protection rule to check the allow_deletions using pygithub.

**Comment by s-t-e-v-e-n-k** [comment] 2021-08-10 12:56
Duplicate of #1716

**Closed by s-t-e-v-e-n-k** 2021-08-10 12:56 UTC
