### ISSUE TITLE
Add support of `allow_auto_merge` attribute to Repository

### ISSUE THREAD

**Issue by BradChengIRESS** [PyGithub/PyGithub#2476] opened 2023-03-27 03:34 UTC
Adds the `allow_auto_merge` attribute to a Repository: https://docs.github.com/en/rest/repos/repos#update-a-repository

> `allow_auto_merge` boolean
> Either `true` to allow auto-merge on pull requests, or `false` to disallow auto-merge.

This attribute can be modified via edit (on a private repository):

```
>>> g.get_repo("<test repo>").allow_auto_merge
True
>>> g.get_repo("<test repo>").edit(allow_auto_merge=False)
>>> g.get_repo("<test repo>").allow_auto_merge
False
>>> g.get_repo("<test repo>").edit(allow_auto_merge=True)
>>> g.get_repo("<test repo>").allow_auto_merge
True
```

**Comment by EnricoMi** [comment] 2023-05-09 10:16
Duplicate of #2456.

**Closed** 2023-05-18 19:33 UTC
